// Direct fake-DOM interaction tests for Query Builder AI Assist state transitions.
import assert from "node:assert/strict";
import test from "node:test";
import { createQueryAssistant } from "../media/gridQueryAssistant.js";

/** Builds an inline DOM element sufficient for assistant form interaction tests. */
function fixture() { const document = { activeElement: undefined, createElement(tag) { const node = { tag, children: [], disabled: false, value: "", listeners: {}, appendChild(child) { this.children.push(child); return child; }, append(...children) { this.children.push(...children); }, addEventListener(type, listener) { (this.listeners[type] ||= []).push(listener); }, dispatch(type, event = {}) { for (const listener of this.listeners[type] || []) { listener({ preventDefault() {}, ...event, target: this }); } }, focus() { document.activeElement = this; }, querySelector(selector) { return find(this, (candidate) => candidate?.id === selector.slice(1)); }, replaceChildren(...children) { this.children = children; }, setAttribute() {} }; return node; } }; const mount = document.createElement("section"); return { document, element: (tag, properties = {}, value) => Object.assign(document.createElement(tag), properties, value === undefined ? {} : { textContent: value }), messages: [], mount }; }
/** Finds one currently mounted fake node. */
function find(node, predicate) { if (predicate(node)) { return node; } for (const child of node.children || []) { const found = find(child, predicate); if (found) { return found; } } return undefined; }
/** Builds one fake authoritative provider snapshot. */
function providers(requestId, settings = { autoUpdateModel: true, model: "", reasoningEffort: "" }, compatibility = "ready") { return { preferredProvider: "claude", providers: [{ available: true, compatibility, generationAllowed: compatibility === "ready" || compatibility === "unverified", label: "Claude Code", metadata: { state: "ready" }, models: [{ label: "sonnet", model: "sonnet", supportedReasoningEfforts: ["low", "medium", "high"] }], provider: "claude", providerReasoningEfforts: ["low", "medium", "high"], settings }], requestId, type: "queryAssistantProviders" }; }
/** Creates an initialized assistant and its mutable test harness. */
function setup({ accepted = [], revision = () => 1 } = {}) { const fake = fixture(); const draft = { computed: [], source: { app: "a", model: "M" } }; const assistant = createQueryAssistant({ element: fake.element, getDraft: () => draft, getRevision: revision, mount: fake.mount, onAccepted: (recipe) => accepted.push(recipe), post: (message) => fake.messages.push(message) }); assistant.onMessage(providers(fake.messages.at(-1).requestId)); return { accepted, assistant, draft, fake }; }
/** Starts one generation and delivers one correlated suggestion. */
function suggest(value, id = "safe") { const input = find(value.fake.mount, (node) => node.id === "queryAssistantInstructions"); input.value = "draft"; input.dispatch("input"); find(value.fake.mount, (node) => node.textContent === "Generate suggestion").dispatch("click"); const generation = value.fake.messages.at(-1); value.assistant.onMessage({ orm: "Model.objects.all()", provider: "claude", requestId: generation.requestId, suggestionId: id, summary: "Safe", type: "queryAssistantSuggestion" }); return value.fake.messages.at(-1); }

test("direct model selection remains busy through its matching snapshot and Automatic retains the pin", () => { const saved = globalThis.document; globalThis.document = fixture().document; try { const value = setup(); const model = find(value.fake.mount, (node) => node.id === "queryAssistantModel"); model.value = "sonnet"; model.dispatch("change"); const pin = value.fake.messages.at(-1); assert.deepEqual({ auto: pin.autoUpdateModel, model: pin.model }, { auto: false, model: "sonnet" }); assert.equal(find(value.fake.mount, (node) => node.id === "queryAssistantModel").disabled, true); value.assistant.onMessage(providers("stale")); assert.equal(find(value.fake.mount, (node) => node.id === "queryAssistantModel").disabled, true); value.assistant.onMessage(providers(pin.requestId, { autoUpdateModel: false, model: "sonnet", reasoningEffort: "high" })); const automatic = find(value.fake.mount, (node) => node.id === "queryAssistantModel"); automatic.value = ""; automatic.dispatch("change"); const restore = value.fake.messages.at(-1); assert.deepEqual({ auto: restore.autoUpdateModel, model: restore.model }, { auto: true, model: "sonnet" }); } finally { globalThis.document = saved; } });

test("provider switch stays disabled until its matching snapshot restores provider-local controls", () => { const saved = globalThis.document; globalThis.document = fixture().document; try { const value = setup(); const record = (provider, model, reasoning) => ({ available: true, compatibility: "ready", generationAllowed: true, label: provider, metadata: { state: "ready" }, models: [{ label: model, model }], provider, providerReasoningEfforts: ["low", "medium", "high"], settings: { autoUpdateModel: false, model, reasoningEffort: reasoning } }); const provider = find(value.fake.mount, (node) => node.id === "queryAssistantProvider"); provider.value = "codex"; provider.dispatch("change"); const request = value.fake.messages.at(-1); assert.equal(find(value.fake.mount, (node) => node.id === "queryAssistantProvider").disabled, true); value.assistant.onMessage({ preferredProvider: "claude", providers: [], requestId: "stale", type: "queryAssistantProviders" }); assert.equal(find(value.fake.mount, (node) => node.id === "queryAssistantProvider").disabled, true); value.assistant.onMessage({ preferredProvider: "codex", providers: [record("claude", "sonnet", "high"), record("codex", "gpt-5", "medium")], requestId: request.requestId, type: "queryAssistantProviders" }); assert.equal(find(value.fake.mount, (node) => node.id === "queryAssistantModel").value, "gpt-5"); assert.equal(find(value.fake.mount, (node) => node.id === "queryAssistantReasoning").value, "medium"); } finally { globalThis.document = saved; } });

test("auto-accept sends exactly once, ignores unrelated errors, and requires a fresh suggestion after failure", () => { const saved = globalThis.document; globalThis.document = fixture().document; try { const value = setup(); const accept = suggest(value); assert.equal(accept.type, "acceptQueryAssistantSuggestion"); assert.equal(value.fake.messages.filter((message) => message.type === "acceptQueryAssistantSuggestion").length, 1); assert.equal(value.assistant.onMessage({ category: "invalid-recipe", requestId: "other", type: "queryAssistantError" }), false); value.assistant.onMessage({ category: "stale", requestId: accept.requestId, type: "queryAssistantError" }); assert.equal(value.fake.messages.filter((message) => message.type === "acceptQueryAssistantSuggestion").length, 1); const fresh = suggest(value, "fresh"); value.assistant.onMessage({ recipe: value.draft, requestId: fresh.requestId, revision: 1, suggestionId: "fresh", type: "queryAssistantAccepted" }); assert.equal(value.accepted.length, 1); } finally { globalThis.document = saved; } });

test("draft invalidation during automatic acceptance prevents mutation and permits a new generation", () => { const saved = globalThis.document; globalThis.document = fixture().document; try { const value = setup(); const accept = suggest(value); value.assistant.invalidate(); value.assistant.onMessage({ recipe: value.draft, requestId: accept.requestId, revision: 1, suggestionId: "safe", type: "queryAssistantAccepted" }); assert.equal(value.accepted.length, 0); assert.equal(find(value.fake.mount, (node) => node.textContent === "Generate suggestion").disabled, false); const next = suggest(value, "fresh"); assert.equal(next.type, "acceptQueryAssistantSuggestion"); } finally { globalThis.document = saved; } });

test("a stale accepted response after revision change never reaches the draft callback", () => { const saved = globalThis.document; globalThis.document = fixture().document; try { let revision = 1; const value = setup({ revision: () => revision }); const accept = suggest(value); revision = 2; value.assistant.onMessage({ recipe: value.draft, requestId: accept.requestId, revision: 1, suggestionId: "safe", type: "queryAssistantAccepted" }); assert.equal(value.accepted.length, 0); } finally { globalThis.document = saved; } });

test("refresh preserves instructions and focus while automatic acceptance is pending", () => { const saved = globalThis.document; globalThis.document = fixture().document; try { const value = setup(); const input = find(value.fake.mount, (node) => node.id === "queryAssistantInstructions"); input.value = "Keep this instruction"; input.dispatch("input"); suggest(value); const refresh = find(value.fake.mount, (node) => node.id === "queryAssistantRefresh"); refresh.focus(); refresh.dispatch("click"); const request = value.fake.messages.at(-1); value.assistant.onMessage(providers("stale")); value.assistant.onMessage(providers(request.requestId)); assert.equal(find(value.fake.mount, (node) => node.id === "queryAssistantInstructions").value, "draft"); assert.equal(value.fake.document.activeElement?.id, "queryAssistantRefresh"); } finally { globalThis.document = saved; } });

test("refresh and model-save failures allow focused retries", () => { const saved = globalThis.document; globalThis.document = fixture().document; try { const value = setup(); const refresh = find(value.fake.mount, (node) => node.id === "queryAssistantRefresh"); refresh.dispatch("click"); const failedRefresh = value.fake.messages.at(-1); value.assistant.onMessage({ category: "provider-failed", requestId: failedRefresh.requestId, terminal: true, type: "queryAssistantError" }); find(value.fake.mount, (node) => node.id === "queryAssistantRefresh").dispatch("click"); const retry = value.fake.messages.at(-1); value.assistant.onMessage(providers(retry.requestId)); const model = find(value.fake.mount, (node) => node.id === "queryAssistantModel"); model.value = "sonnet"; model.dispatch("change"); const failedSave = value.fake.messages.at(-1); value.assistant.onMessage({ category: "settings-write-failed", requestId: failedSave.requestId, terminal: true, type: "queryAssistantError" }); find(value.fake.mount, (node) => node.id === "queryAssistantModel").dispatch("change"); assert.equal(value.fake.messages.at(-1).type, "updateQueryAssistantProviderSettings"); } finally { globalThis.document = saved; } });

test("external settings synchronization during automatic acceptance invalidates the pending result", () => { const saved = globalThis.document; globalThis.document = fixture().document; try { const value = setup(); const accept = suggest(value); const external = providers(undefined, { autoUpdateModel: false, model: "gpt-5", reasoningEffort: "medium" }); external.preferredProvider = "codex"; external.providers[0] = { ...external.providers[0], label: "Codex", models: [{ label: "GPT-5", model: "gpt-5" }], provider: "codex" }; value.assistant.onMessage({ ...external, settingsSync: true }); value.assistant.onMessage({ recipe: value.draft, requestId: accept.requestId, revision: 1, suggestionId: "safe", type: "queryAssistantAccepted" }); assert.equal(value.accepted.length, 0); assert.ok(find(value.fake.mount, (node) => node.id === "queryAssistantStale")); } finally { globalThis.document = saved; } });
