// Behavioral tests for bounded Query Builder assistant protocol normalization.
import assert from "node:assert/strict";
import test from "node:test";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url); const protocol = require("../out/modelQueryAssistantProtocol.js"); const recipe = require("../out/modelQueryRecipe.js");
test("normalizes the valid generation message and strips excess instruction text", () => { const value = protocol.parseQueryAssistantMessage({ type: "generateQueryAssistantSuggestion", requestId: "r", provider: "codex", instruction: `  ${"x".repeat(12001)}  `, recipe: recipe.createEmptyModelQueryRecipe({ app: "a", model: "M" }), revision: 2, ignored: true }); assert.equal(value.provider, "codex"); assert.ok(value.instruction.length <= 12000); assert.equal(value.revision, 2); });
test("rejects invalid identity, revision, provider, and recipe containers", () => { for (const value of [{ type: "queryAssistantProviders", requestId: "" }, { type: "generateQueryAssistantSuggestion", requestId: "r", provider: "auto", instruction: "x", recipe: {}, revision: 0 }, { type: "acceptQueryAssistantSuggestion", requestId: "r", suggestionId: "s", revision: -1 }]) { assert.equal(protocol.parseQueryAssistantMessage(value), undefined); } });
test("normalizes bounded provider settings messages without accepting argv fragments", () => { const message = protocol.parseQueryAssistantMessage({ type: "updateQueryAssistantProviderSettings", requestId: "r", provider: "codex", autoUpdateModel: false, model: "gpt-5.1", reasoningEffort: "xhigh" }); assert.deepEqual(message, { type: "updateQueryAssistantProviderSettings", requestId: "r", provider: "codex", autoUpdateModel: false, model: "gpt-5.1", reasoningEffort: "xhigh" }); assert.equal(protocol.parseQueryAssistantMessage({ type: "updateQueryAssistantProviderSettings", requestId: "r", provider: "codex", autoUpdateModel: false, model: "gpt 5", reasoningEffort: "xhigh" }), undefined); });
test("rejects every non-string model input before clipping or trimming", () => { for (const value of [undefined, null, 1, {}, [], true]) { assert.equal(protocol.normalizeAssistantModel(value), undefined); } assert.equal(protocol.normalizeAssistantModel("  gpt-5  "), "gpt-5"); assert.equal(protocol.normalizeAssistantModel("--model gpt-5"), undefined); });
