// Direct lifecycle tests for opaque Query Builder assistant host suggestions.
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import test from "node:test";
const require = createRequire(import.meta.url); const { createModelQueryAssistantHost } = require("../out/modelQueryAssistantHost.js"); const { createEmptyModelQueryRecipe } = require("../out/modelQueryRecipe.js");
/** Creates a host fixture with mutable source/revision and controllable provider work. */
function fixture(overrides = {}) { const source = { app: "a", model: "M" }; const draft = createEmptyModelQueryRecipe(source); const sent = []; let revision = 1; let context = { source }; const generated = []; const service = { detectProviders: async () => [{ available: true, label: "Codex", provider: "codex" }], generate: (_provider, _prompt, signal) => new Promise((resolve, reject) => generated.push({ reject, resolve, signal })) }; const host = createModelQueryAssistantHost({ capture: () => ({ context, revision, source }), onSettings: () => undefined, post: (message) => sent.push(message), service, validate: async (recipe) => ({ normalized: recipe, ok: true, orm: "Model.objects.all()", summary: "All rows", warnings: [] }), ...overrides }); const message = (requestId) => ({ type: "generateQueryAssistantSuggestion", requestId, provider: "codex", instruction: "help", recipe: draft, revision }); return { draft, generated, host, message, sent, setContext: (value) => { context = value; }, setRevision: (value) => { revision = value; } }; }

test("host detects providers, stores opaque suggestion, and accepts only after fresh validation", async () => { const value = fixture(); await value.host.handleMessage({ type: "queryAssistantProviders", requestId: "providers" }); assert.equal(value.sent.at(-1).type, "queryAssistantProviders"); const run = value.host.handleMessage(value.message("generate")); await Promise.resolve(); value.generated[0].resolve(JSON.stringify({ recipe: value.draft })); await run; const suggestion = value.sent.find((message) => message.type === "queryAssistantSuggestion"); assert.ok(suggestion?.suggestionId); await value.host.handleMessage({ type: "acceptQueryAssistantSuggestion", requestId: "accept", suggestionId: suggestion.suggestionId, revision: 1 }); assert.equal(value.sent.at(-1).type, "queryAssistantAccepted"); });
test("a second generation aborts and replaces the first while its late output is ignored", async () => { const value = fixture(); const first = value.host.handleMessage(value.message("first")); await Promise.resolve(); const second = value.host.handleMessage(value.message("second")); await Promise.resolve(); assert.equal(value.generated[0].signal.aborted, true); value.generated[0].resolve(JSON.stringify({ recipe: value.draft })); value.generated[1].resolve(JSON.stringify({ recipe: value.draft })); await Promise.all([first, second]); assert.equal(value.sent.filter((message) => message.type === "queryAssistantSuggestion").length, 1); assert.equal(value.sent.at(-1).requestId, "second"); });
test("explicit cancellation aborts and suppresses late provider output", async () => { const value = fixture(); const run = value.host.handleMessage(value.message("cancel")); await Promise.resolve(); await value.host.handleMessage({ type: "cancelQueryAssistantSuggestion", requestId: "cancel" }); value.generated[0].resolve(JSON.stringify({ recipe: value.draft })); await run; assert.equal(value.generated[0].signal.aborted, true); assert.equal(value.sent.some((message) => message.type === "queryAssistantSuggestion"), false); assert.equal(value.sent.at(-1).type, "queryAssistantCancelled"); });
test("schema or source invalidation suppresses a stale generated result", async () => { const value = fixture(); const run = value.host.handleMessage(value.message("stale")); await Promise.resolve(); value.host.invalidate("schema"); value.generated[0].resolve(JSON.stringify({ recipe: value.draft })); await run; assert.equal(value.sent.some((message) => message.type === "queryAssistantSuggestion"), false); });
test("dispose aborts active work and suppresses late provider output", async () => { const value = fixture(); const run = value.host.handleMessage(value.message("dispose")); await Promise.resolve(); value.host.dispose(); value.generated[0].resolve(JSON.stringify({ recipe: value.draft })); await run; assert.equal(value.generated[0].signal.aborted, true); assert.equal(value.sent.some((message) => message.type === "queryAssistantSuggestion"), false); });
test("provider detection and settings failures return bounded errors without throwing", async () => { const value = fixture({ onSettings: async () => { throw new Error("raw settings error"); }, service: { detectProviders: async () => { throw new Error("raw provider error"); }, generate: async () => "" } }); await value.host.handleMessage({ type: "queryAssistantProviders", requestId: "providers" }); await value.host.handleMessage({ type: "openQueryAssistantSettings" }); assert.deepEqual(value.sent.map((message) => message.category), ["provider-unavailable", "provider-failed"]); });
test("accept capture or validation rejection returns a bounded category without raw errors", async () => { const source = { app: "a", model: "M" }; const draft = createEmptyModelQueryRecipe(source); const sent = []; let captureFails = false; let validationFails = false; const host = createModelQueryAssistantHost({ capture: () => { if (captureFails) { throw new Error("secret capture failure"); } return { context: { source }, revision: 1, source }; }, onSettings: () => undefined, post: (message) => sent.push(message), service: { detectProviders: async () => [], generate: async () => JSON.stringify({ recipe: draft }) }, validate: async (recipe) => { if (validationFails) { throw new Error("secret validation failure"); } return { normalized: recipe, ok: true }; } }); await host.handleMessage({ type: "generateQueryAssistantSuggestion", requestId: "generate", provider: "codex", instruction: "help", recipe: draft, revision: 1 }); const suggestion = sent.find((message) => message.type === "queryAssistantSuggestion"); captureFails = true; await host.handleMessage({ type: "acceptQueryAssistantSuggestion", requestId: "capture", suggestionId: suggestion.suggestionId, revision: 1 }); assert.equal(sent.at(-1).category, "invalid-recipe"); captureFails = false; validationFails = true; await host.handleMessage({ type: "acceptQueryAssistantSuggestion", requestId: "validate", suggestionId: suggestion.suggestionId, revision: 1 }); assert.equal(sent.at(-1).category, "invalid-recipe"); assert.equal(JSON.stringify(sent).includes("secret"), false); });
test("immediate relation-draft generation prepares descriptors before provider invocation without query execution", async () => { const source = { app: "a", model: "M" }; const draft = createEmptyModelQueryRecipe(source); draft.where.children.push({ correlations: [], kind: "existsPredicate", negated: false, nodeId: "exists", source: { kind: "relation", relation: "items" }, where: { children: [], join: "and", kind: "group", negated: false, nodeId: "inner" } }); let prepared = false; let providerPrompt = ""; const host = createModelQueryAssistantHost({ capture: () => ({ context: { relatedModels: prepared ? [{ app: "a", columns: [{ name: "visible" }], model: "Item", relations: [{ name: "children" }] }] : [], source }, revision: 2, source }), onSettings: () => undefined, post: () => undefined, prepare: async () => { prepared = true; }, service: { detectProviders: async (_provider, prompt) => { providerPrompt = prompt; return JSON.stringify({ recipe: draft }); }, generate: async (_provider, prompt) => { providerPrompt = prompt; return JSON.stringify({ recipe: draft }); } }, validate: async (recipe) => ({ normalized: recipe, ok: true }) }); await host.handleMessage({ type: "generateQueryAssistantSuggestion", requestId: "immediate", provider: "codex", instruction: "help", recipe: draft, revision: 2 }); const context = JSON.parse(providerPrompt.match(/UNTRUSTED_QUERY_CONTEXT_JSON\n(.*)\nEND_UNTRUSTED_QUERY_CONTEXT_JSON/)?.[1] ?? "{}"); assert.equal(prepared, true); assert.equal(context.relatedModels[0].columns[0].name, "visible"); assert.equal(context.rows, undefined); });
test("malformed generation is not consumed and a later valid revision remains current", async () => { const value = fixture(); assert.equal(await value.host.handleMessage({ type: "generateQueryAssistantSuggestion", requestId: "", provider: "invalid", instruction: "", recipe: value.draft, revision: 999 }), false); const run = value.host.handleMessage(value.message("valid")); await Promise.resolve(); value.generated[0].resolve(JSON.stringify({ recipe: value.draft })); await run; assert.equal(value.sent.some((message) => message.type === "queryAssistantSuggestion"), true); });
test("settings select, refresh, busy, and write failure all return authoritative bounded snapshots", async () => {
  const source = { app: "a", model: "M" }; const draft = createEmptyModelQueryRecipe(source); const sent = []; let configured; let refreshes = 0; let release; const pending = new Promise((resolve) => { release = resolve; }); const service = { configure: async (provider, settings) => { configured = { provider, settings }; }, detectProviders: async (refresh = false) => { refreshes += Number(refresh); return { preferredProvider: "codex", providers: [{ available: true, provider: "codex" }] }; }, generate: async () => pending };
  const host = createModelQueryAssistantHost({ capture: () => ({ context: { source }, revision: 1, source }), onSettings: () => undefined, post: (message) => sent.push(message), service, validate: async (recipe) => ({ normalized: recipe, ok: true }) });
  await host.handleMessage({ type: "selectQueryAssistantProvider", requestId: "select", provider: "codex" }); await host.handleMessage({ type: "updateQueryAssistantProviderSettings", requestId: "save", provider: "codex", autoUpdateModel: false, model: "gpt-5", reasoningEffort: "high" }); await host.handleMessage({ type: "refreshQueryAssistantProviders", requestId: "refresh" });
  assert.deepEqual(configured, { provider: "codex", settings: { autoUpdateModel: false, model: "gpt-5", reasoningEffort: "high" } }); assert.equal(refreshes, 1);
  const generation = host.handleMessage({ type: "generateQueryAssistantSuggestion", requestId: "run", provider: "codex", instruction: "help", recipe: draft, revision: 1 }); await Promise.resolve(); await host.handleMessage({ type: "selectQueryAssistantProvider", requestId: "busy", provider: "codex" }); assert.equal(sent.at(-1).category, "settings-busy"); release(JSON.stringify({ recipe: draft })); await generation;
});
test("terminal detection, refresh, and settings-busy errors permit the webview to retry", async () => {
  const value = fixture({ service: { detectProviders: async () => { throw new Error("nope"); }, generate: async () => "" } });
  await value.host.handleMessage({ type: "queryAssistantProviders", requestId: "detect" }); await value.host.handleMessage({ type: "refreshQueryAssistantProviders", requestId: "refresh" });
  assert.deepEqual(value.sent.map((message) => [message.requestId, message.terminal]), [["detect", true], ["refresh", true]]);
  const busy = fixture(); const run = busy.host.handleMessage(busy.message("run")); await Promise.resolve(); await busy.host.handleMessage({ type: "selectQueryAssistantProvider", requestId: "settings", provider: "codex" }); assert.equal(busy.sent.at(-1).terminal, true); busy.generated[0].resolve(JSON.stringify({ recipe: busy.draft })); await run;
});
test("settings failure posts error then snapshot, or a terminal bounded error if reread fails", async () => {
  const source = { app: "a", model: "M" }; const make = (detect) => { const sent = []; return { sent, host: createModelQueryAssistantHost({ capture: () => ({ context: { source }, revision: 1, source }), onSettings: () => undefined, post: (message) => sent.push(message), service: { configure: async () => { throw new Error("secret"); }, detectProviders: detect, generate: async () => "" }, validate: async () => ({ ok: false }) }) }; };
  const recovered = make(async () => ({ providers: [] })); await recovered.host.handleMessage({ type: "selectQueryAssistantProvider", requestId: "recover", provider: "codex" }); assert.deepEqual(recovered.sent.map((message) => message.type), ["queryAssistantError", "queryAssistantProviders"]); assert.equal(recovered.sent[0].category, "settings-write-failed");
  const terminal = make(async () => { throw new Error("secret reread"); }); await terminal.host.handleMessage({ type: "selectQueryAssistantProvider", requestId: "terminal", provider: "codex" }); assert.equal(terminal.sent.at(-1).terminal, true); assert.equal(JSON.stringify(terminal.sent).includes("secret"), false);
});
test("external configuration changes coalesce, invalidate stale suggestions, and stop after disposal", async () => {
  const source = { app: "a", model: "M" }; const draft = createEmptyModelQueryRecipe(source); const sent = []; let listener; let preferred = "claude"; let detections = 0;
  const host = createModelQueryAssistantHost({ capture: () => ({ context: { source }, revision: 1, source }), onSettings: () => undefined, post: (message) => sent.push(message), service: { detectProviders: async () => { detections += 1; return { preferredProvider: preferred, providers: [{ provider: preferred, settings: { autoUpdateModel: false, model: preferred === "codex" ? "gpt-5" : "sonnet", reasoningEffort: "high" } }] }; }, generate: async () => JSON.stringify({ recipe: draft }), onDidChangeConfiguration: (callback) => { listener = callback; return { dispose: () => { listener = undefined; } }; } }, validate: async (recipe) => ({ normalized: recipe, ok: true }) });
  await host.handleMessage({ type: "queryAssistantProviders", requestId: "initial" }); await host.handleMessage({ type: "generateQueryAssistantSuggestion", requestId: "generate", provider: "claude", instruction: "help", recipe: draft, revision: 1 }); assert.ok(sent.some((message) => message.type === "queryAssistantSuggestion")); preferred = "codex"; listener(); listener(); await new Promise((resolve) => setTimeout(resolve, 0)); assert.equal(detections, 2); assert.equal(sent.filter((message) => message.settingsSync).length, 1); assert.equal(sent.some((message) => message.category === "stale" && !message.requestId), true); host.dispose(); listener?.(); await new Promise((resolve) => setTimeout(resolve, 0)); assert.equal(detections, 2);
});
