// Stable, user-facing validation issue presentation for Model Query Builder.

import { sentenceCase } from "./gridQueryGuidanceCopy.js";

/** Builds frozen title/explanation records from the validation contract's stable codes. */
function entries(records) { return Object.freeze(Object.fromEntries(records.map(([code, title, explanation]) => [code, Object.freeze({ title, explanation })]))); }

/** Every current validator code mapped to concise action-oriented user guidance. */
export const QUERY_ISSUE_GUIDANCE = entries([
  ["RECIPE_VERSION_UNSUPPORTED", "This query format is not supported", "The draft was created with a Recipe version this builder cannot apply."], ["RECIPE_SOURCE_MISMATCH", "This query belongs to another model", "The draft source does not match the model currently open in the grid."], ["RECIPE_TOO_LARGE", "This query is too large", "The complete draft exceeds the bounded Recipe payload size."], ["RECIPE_SHAPE_INVALID", "Part of the query is incomplete", "A required group, item, or value has an unsupported shape."], ["NODE_ID_INVALID", "A query item has an invalid identifier", "Stable internal identifiers must use the bounded generated format."], ["NODE_ID_DUPLICATE", "Two query items share an identifier", "Every query item needs a unique stable identifier."],
  ["PREDICATE_NODE_LIMIT", "There are too many conditions", "The query exceeds the maximum number of predicate nodes."], ["PREDICATE_GROUP_DEPTH_LIMIT", "Conditions are nested too deeply", "The query exceeds the maximum nested group depth."], ["PREDICATE_GROUP_CHILD_LIMIT", "This group has too many items", "A single group can contain only the bounded number of children."], ["EMPTY_NESTED_GROUP", "This nested group is empty", "Only the root group may be empty; an empty nested group has no useful meaning."], ["FIELD_METADATA_UNAVAILABLE", "Field details are unavailable", "The builder cannot safely validate paths and types without current model metadata."], ["FIELD_PATH_INVALID", "Choose an available field", "The selected path is not present in the current model metadata."], ["FIELD_PATH_TOO_LONG", "This field path is too long", "The relation traversal exceeds the bounded path length or segment count."], ["FIELD_PATH_RELATION_TERMINAL", "Choose a field inside this relation", "This comparison needs a scalar field unless it is checking whether a relation is null."], ["FIELD_PATH_TO_MANY_UNSAFE", "This to-many path is unsafe here", "Following this relation can duplicate source rows in a context that cannot preserve the intended result."],
  ["LOOKUP_UNSUPPORTED", "Choose a supported comparison", "The selected lookup is not in the Recipe allowlist."], ["LOOKUP_TYPE_MISMATCH", "This comparison does not fit the field type", "The selected lookup cannot be used with this field’s Django type."], ["RHS_KIND_UNSUPPORTED", "Choose a supported value source", "This context cannot compare against the selected value, field, OuterRef, or relative time kind."], ["RHS_TYPE_MISMATCH", "The comparison values have different types", "The right-hand value cannot be safely compared with the selected field."], ["VALUE_REQUIRED", "Enter a comparison value", "This comparison cannot be evaluated without a value."], ["VALUE_INVALID", "Enter a valid value", "The value cannot be converted to the selected field and lookup type."], ["IN_LIST_LIMIT", "The value list is too long", "The in comparison exceeds the bounded list size."], ["RELATIVE_TIME_INVALID", "Complete the relative time", "Amount, unit, anchor, or direction is outside the supported range."],
  ["COMPUTED_COLUMN_LIMIT", "There are too many calculated values", "The draft exceeds the maximum number of computed columns."], ["ALIAS_INVALID", "Use a valid calculated-value name", "Aliases use a bounded Python-style identifier format."], ["ALIAS_RESERVED", "Choose a different calculated-value name", "This alias is reserved by the query or model runtime."], ["ALIAS_COLLISION", "This name conflicts with a model field", "A calculated value cannot hide an existing model field."], ["ALIAS_DUPLICATE", "This calculated-value name is already used", "Every enabled computed column needs a unique alias."], ["COMPUTED_REFERENCE_UNKNOWN", "Choose an available calculated value", "The referenced alias does not exist in this draft."], ["COMPUTED_REFERENCE_FORWARD", "Move the dependency above this formula", "A formula can use only enabled calculated values declared earlier in the list."], ["COMPUTED_REFERENCE_DISABLED", "Enable the referenced calculated value", "This expression depends on a computed column that is currently disabled."], ["COMPUTED_KIND_UNSUPPORTED_IN_SUMMARY", "This calculated value is not available in Summary", "Summary mode supports only the existing aggregate-compatible computed kinds."],
  ["AGGREGATE_FIELD_REQUIRED", "Choose a value to summarize", "This aggregate function needs a field or the supported all-rows form."], ["AGGREGATE_FANOUT_UNSAFE", "This aggregate can duplicate values", "The selected to-many path can multiply rows and change the aggregate result."], ["AGGREGATE_DISTINCT_UNSUPPORTED", "DISTINCT is not supported for this aggregate", "The selected function and distinct mode are not a supported combination."], ["WINDOW_ORDER_REQUIRED", "Choose an order for the window calculation", "Window results require a stable row sequence."], ["WINDOW_FILTER_UNSUPPORTED", "Window values cannot be filtered here", "The current query pipeline cannot apply this result filter to a window alias."], ["FORMULA_NODE_LIMIT", "This formula has too many parts", "The expression tree exceeds the bounded node count."], ["FORMULA_DEPTH_LIMIT", "This formula is nested too deeply", "The expression tree exceeds the bounded depth."], ["FORMULA_TYPE_MISMATCH", "Formula values have incompatible types", "The selected operation or function cannot combine these input types safely."], ["FORMULA_DIVIDE_BY_ZERO", "The formula divides by zero", "A fixed divisor of zero cannot produce a valid result."], ["OUTPUT_TYPE_REQUIRED", "Choose the result type", "The builder needs an output type to validate and compile this expression."],
  ["RAW_EXPRESSION_INVALID", "The restricted expression is not valid", "The expression contains unsupported syntax, names, or structure."], ["RAW_EXPRESSION_TRANSPORT_UNSUPPORTED", "This link cannot run the restricted expression", "The active transport does not support this advanced expression form."], ["RAW_MODEL_NAME_AMBIGUOUS", "Use an unambiguous model reference", "The restricted expression refers to a model name that cannot be resolved safely."], ["SUBQUERY_SOURCE_INVALID", "Choose a subquery source", "The subquery needs a valid relation or app-qualified model."], ["SUBQUERY_RELATION_INVALID", "Choose an available relation", "The selected relation is not present on the current source model."], ["SUBQUERY_CORRELATION_REQUIRED", "Connect the target to the current row", "A custom-model subquery needs at least one complete correlation."], ["SUBQUERY_CORRELATION_LIMIT", "There are too many subquery connections", "The subquery exceeds the bounded correlation count."], ["SUBQUERY_CORRELATION_INVALID", "Complete this subquery connection", "The target and current-row paths are missing or incompatible."], ["SUBQUERY_SELECT_INVALID", "Choose the value returned by the subquery", "The subquery select field or aggregate is incomplete or unsupported."], ["SUBQUERY_ORDER_LIMIT", "There are too many subquery order terms", "The subquery exceeds the bounded inner order count."], ["SUBQUERY_IMPLICIT_ORDER", "The subquery uses its default order", "No explicit inner order is set, so the target primary key ascending is used."], ["SUBQUERY_AGGREGATE_FANOUT_UNSAFE", "This subquery aggregate can duplicate values", "The selected target path can multiply rows before aggregation."], ["OUTER_REF_SCOPE_INVALID", "Choose a field from the current outer row", "This OuterRef points outside the scope available to the subquery."],
  ["GLOBAL_SUMMARY_POST_FILTER_UNSUPPORTED", "This global summary filter is not supported", "The current result filter needs grouping or a supported summary alias context."], ["PYTHON_PROPERTY_FULL_SCAN", "This filter scans Python values in memory", "The property is not a database field, so normal indexed filtering and pagination are unavailable."], ["PYTHON_PROPERTY_BOOLEAN_UNSUPPORTED", "This Python property cannot use this boolean filter", "The property value cannot be translated to the requested database boolean operation."], ["PYTHON_PROPERTY_SUMMARY_UNSUPPORTED", "Python properties are not available in Summary", "Summary mode must run in the database and cannot group or aggregate arbitrary Python properties."], ["AUTO_DISTINCT_APPLIED", "Duplicate source rows will be removed", "The builder adds DISTINCT because a to-many relation could otherwise duplicate the current model rows."], ["OFFSET_PAGINATION_REQUIRED", "This query uses offset pagination", "Calculated values, windows, or custom ordering prevent primary-key keyset pagination."], ["TRANSPORT_CAPABILITY_UNSUPPORTED", "The active link cannot run this query", "The draft uses a feature not supported by the selected transport."], ["GENERATED_QUERY_TOO_LARGE", "The generated Django query is too large", "The validated Recipe expands beyond the bounded executable ORM cell size."]
]);

/** Presents a validation issue with safe fallbacks for newer backend issue codes. */
export function presentQueryIssue(issue = {}) {
  const guidance = QUERY_ISSUE_GUIDANCE[issue.code];
  return {
    title: guidance?.title || sentenceCase(issue.code || "Query issue"),
    explanation: guidance?.explanation || String(issue.message || "The query needs attention before it can be applied."),
    fix: String(issue.fix || "Review the highlighted query setting."),
    severity: issue.severity === "warning" ? "warning" : "error",
    technical: { code: String(issue.code || ""), path: String(issue.path || "") }
  };
}
